UnitexGramLab/gramlab-ide

unitex/src/fr/umlv/unitex/frames/TextAutomatonFrame.java

This resolves Issue #9: Resizing the window that displays the text automaton.

Add EmptyBorder at the bottom in TextAutomatonFrame

---

unitex/src/fr/umlv/unitex/graphrendering/GraphicalZone.java

This commit modifies the default text of a newly created generic graph
marker box.

Update default text

---

unitex/src/fr/umlv/unitex/config/Config.java
unitex/src/fr/umlv/unitex/frames/GraphPathDialog.java
unitex/src/fr/umlv/unitex/frames/InternalFrameManager.java
unitex/src/fr/umlv/unitex/frames/UnitexFrame.java

invoking Explore graph paths menu option

issue #61 changes to allow user to set the name of the output file when

---

unitex/src/fr/umlv/unitex/diff/GraphDecorator.java
unitex/src/fr/umlv/unitex/diff/GraphDecoratorConfig.java
unitex/src/fr/umlv/unitex/graphrendering/GenericGraphBox.java
unitex/src/fr/umlv/unitex/graphrendering/TfstGraphBox.java

Update the colors of the text automaton to match those described in #59. (Korean only)

[Feature #59] Colour marking in the text automaton

---

unitex/src/fr/umlv/unitex/cassys/TransducerListTableModel.java
unitex/src/fr/umlv/unitex/config/Config.java
unitex/src/fr/umlv/unitex/frames/CassysFrame.java
unitex/src/fr/umlv/unitex/frames/GraphFrame.java
unitex/src/fr/umlv/unitex/frames/TransducerListConfigurationFrame.java
unitex/src/fr/umlv/unitex/frames/UnitexFrame.java
unitex/src/fr/umlv/unitex/graphrendering/GraphBox.java
unitex/src/fr/umlv/unitex/graphrendering/GraphicalZone.java
unitex/src/fr/umlv/unitex/process/commands/Grf2Fst2Command.java

This is an experimental feature. This tool tries to see if the braces: "{" and "}" are well formed in the output.

New tool for graph

---

unitex/src/fr/umlv/unitex/diff/GraphDecorator.java
unitex/src/fr/umlv/unitex/diff/GraphDecoratorConfig.java
unitex/src/fr/umlv/unitex/frames/TextAutomatonFindAndReplaceDialog.java
unitex/src/fr/umlv/unitex/frames/TextAutomatonFrame.java
unitex/src/fr/umlv/unitex/frames/UnitexFrame.java

Update the "Find & Replace" feature for the text automaton.
+ Now works on the whole automaton
+ New highlight color (Korean)

Update Find & Replace tfst

---

unitex/src/fr/umlv/unitex/frames/TextAutomatonFindAndReplaceDialog.java
unitex/src/fr/umlv/unitex/frames/TextAutomatonFindAndReplaceDialogFactory.java
unitex/src/fr/umlv/unitex/frames/TextAutomatonTagFilterDialog.java
unitex/src/fr/umlv/unitex/frames/TextAutomatonTagFilterDialogFactory.java
unitex/src/fr/umlv/unitex/tfst/TfstTagFilter.java
unitex/src/fr/umlv/unitex/utils/CharsetDetector.java

In response to a comment by martinec concerning PR #72, added the missing LGPL disclaimer to .java files.

Add the LGPL disclaimer to new .java files

---

unitex/src/fr/umlv/unitex/frames/TextAutomatonFrame.java

Fix issue #33. 
This issue was fixed with PR #34 but the changes were later deleted with commit https://github.com/UnitexGramLab/gramlab-ide/commit/c46754f241c3a1009f50c96968c5769cd4663c66.

[minor refactor #33] Rename Reset Sentence Graph and Rebuild FST-Text

---

unitex/src/fr/umlv/unitex/frames/GraphFrame.java

Add a button that copy the list of called sub graphs to the clipboard.
As stated in the issue, it is interesting to copy the list of called sub graph to perform further operations.
I have tested these changes on Windows 10 using the graph Sentence.grf (French). These changes should not affect other areas of the code.

[feature #6] Add a button to copy the list of called sub(sub)*-graphs to the clipboard

---

unitex/src/fr/umlv/unitex/frames/GraphFrame.java

This fix will count the presence of subgraph B as an opening brace.

[minor fix] Count subgraph as brace

---

unitex/src/fr/umlv/unitex/frames/LocateFrame.java

This fix will allow Unitex to display 0 match if the query is an empty grammar, it also resolves the null pointer exception.
Fix for issue #70.
I have tested these changes on Windows 10 using the provided graph (cul-de-sac.grf) in #70 . These changes should not affect other areas of the code.

[fix #70] Fix null exception in Locate Pattern

---

unitex/src/fr/umlv/unitex/tfst/tagging/TaggingModel.java

This fix resolves the Illegal State Exception in FST-Text when deleting a transition.
Fix for issue #88 
I have tested these changes on Windows 10 using the text 80jours.txt. Setting the tagging state to neutral should not affect other areas of the code because the neutral state means there is nothing to do for the current box. 

[fix #88] Fix exception when deleting a transition

---

unitex/src/fr/umlv/unitex/diff/GraphDecorator.java
unitex/src/fr/umlv/unitex/diff/GraphDecoratorConfig.java
unitex/src/fr/umlv/unitex/graphrendering/GenericGraphBox.java
unitex/src/fr/umlv/unitex/graphrendering/TfstGraphBox.java

Requested by Eric Laporte in his issue #109.
Works on Debian 8.

Applied korean coloring to all other languages

---

unitex/src/fr/umlv/unitex/frames/GraphFrame.java

Correct typo in the code used by `verify braces` function.
`Verify braces` relies on `Fst2List` to parse the graph. As the `Fst2List` output was modified by [Fst2List refactor](https://github.com/UnitexGramLab/unitex-core/pull/55) `verify braces` needed an update.
This has been tested on graphs with braces error.

[minor fix] Correct typo in verify braces code

---

unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java

Changing the graph `explore graph paths` was called on makes no sense and may lead to confusions as well as bugs.
No tests required.

[minor fix] Make the graph name text area uneditable in `explore graph paths`

---

unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java
unitex/src/fr/umlv/unitex/frames/UnitexFrame.java

Add option to flatten the graph before exploring it.
See #115.
Add a checkbox to flatten the graph.
Add a button to show the options available for flattening.
Allow Flatten Frame to be used outside from Compile & Flatten.
It is not currently possible to flatten graphs before exploring them as they are recompiled (without flattening) every time we explore them.
This has been tested on various graphs available in Unitex/GramLab.

[feature] Add option to flatten graph when using `explore grapth paths`

---

unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java
unitex/src/fr/umlv/unitex/process/commands/Fst2ListCommand.java

Add a checkbox in _explore graph paths_ frame to enable or disable loop check before graph exploration.
Loop check is currently enable by default with no way to disable it.
See #120.
Tested on Debian 9.5 on _DnumBillion.grf_.

[feature] Add checkbox to Explore Grapth Paths to control loop check

---

unitex/src/fr/umlv/unitex/frames/GraphPathFrame.form
unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java
unitex/src/fr/umlv/unitex/frames/InternalFrameManager.java

Redesign the Explore graph path frame to make it easier to read and improve UX/UI.
A lot of buttons were added to the frame (e.g. [PR 121](https://github.com/UnitexGramLab/gramlab-ide/pull/121) and [PR 116](https://github.com/UnitexGramLab/gramlab-ide/pull/116)) and made it quite busy and hard to use.
The '._form_' file used by Netbeans GUI is added to make future changes easier as this was made under Netbeans.
Various user cases exploring graphs.

[feature #122] Redesign explore graph frame

---

unitex/src/fr/umlv/unitex/utils/HelpMenuBuilder.java

 [fix #125] Allow to open URLs from the Help menu on Linux

---

README.md
unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java
unitex/src/fr/umlv/unitex/process/commands/Fst2ListCommand.java

Add an option "-K" for Fst2List, to detect if Unitex is launched in korean.
This PR refers issue #131 and is associated with PR 88 of unitex-core.
This PR fixes the issue 87 of unitex-core.
See PR 88 in unitex-core.

[enhance] Add argument for korean in explore graph paths

---

unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java
unitex/src/fr/umlv/unitex/process/commands/Fst2ListCommand.java

Add an argument "-D _name"_ to give the list of morphological dictionaries specified by the user in Preferences.
This PR refers the PR 91 of unitex-core for lexical masks processing
Fst2List requires this list to process the lexical masks.
See PR 91 of unitex-core

[enhance #132] Add arguments to give the list of morphological dictionaries to Fst2List

---

unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java
unitex/src/fr/umlv/unitex/process/commands/Fst2ListCommand.java

[enhance] Improve korean graph paths exploring

---

unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java
unitex/src/fr/umlv/unitex/process/commands/Fst2ListCommand.java

This PR solve Issue #134 
Add a button "process as dictionary-graph".
When this option is checked, the programm use option -P :
- Outputs options (ignore, separate, alternate) are no longer used.
- Use merge/replace mode according the graph's name
- The output file format become .dic instead of .txt
Merge and replace modes are necessary to get a valid .dic output file.

[enhance #134] Add option create .dic output file and apply merge/replace mode

---

unitex/src/fr/umlv/unitex/frames/GraphPathFrame.java
unitex/src/fr/umlv/unitex/process/commands/Fst2ListCommand.java

This PR  adds a "process as dictionary-graph" button for
explore graph paths. When this option is checked, the UI uses
the option -P for Fst2List, i.e:
- Outputs options (ignore, separate, alternate) are no longer used
- Use merge/replace mode according the graph's name
- The output file format become .dic instead of .txt
Resolves #134
See also #136

[enhance #134] Add an option to create a . dic output and apply in merge/replace mode

---

unitex/src/fr/umlv/unitex/config/UserPreferences.java
unitex/src/fr/umlv/unitex/frames/InternalFrameManager.java
unitex/src/fr/umlv/unitex/leximir/delas/EditorDelas.java
unitex/src/fr/umlv/unitex/leximir/delas/menu/MenuDelas.java
unitex/src/fr/umlv/unitex/leximir/helper/CsvOpener.java
unitex/src/fr/umlv/unitex/leximir/helper/CsvOpenerFactory.java
unitex/src/fr/umlv/unitex/leximir/helper/DelasHelper.java
unitex/src/fr/umlv/unitex/leximir/helper/GridHelper.java
unitex/src/fr/umlv/unitex/leximir/helper/StatisticOutput.java
unitex/src/fr/umlv/unitex/leximir/util/DuplicationFinder.java

This is the application of the review recommendations of the [PR#130](https://github.com/UnitexGramLab/gramlab-ide/pull/130).
It is mostly conventions applications like changing variable names or removing useless spaces and blanks.
Context constrained to merge the PR#130 without apply the review changes. This PR is fixing it.
No tests were needed because this is a simple refactor.

[refactor] Resolve issues on LeXimir branch after PR #130

---

unitex/src/fr/umlv/unitex/config/Config.java

Resolve NPE when clicking on Set File button (Explore Graph Paths menu)
Fix NullPointerException when clicking on Set File button (Explore Graph Paths menu), for the first time.
Initializes sentenceDialogBox if it is not initialized in getExploreGraphOutputDialogBox method.
End of line spaces are removed using the .editorconfig file.
[issue 128](https://github.com/UnitexGramLab/gramlab-ide/issues/128) - NullPointerException when clicking on Set File button (Explore Graph Paths menu)
This has been tested using Dnum-ch.grf.

[fix #128] Resolve NullPointerException

---

.github/CONTRIBUTING.md
README.md

In instructions for testing, mention where the language directories must be copied (issue #166).
Update README.md and CONTRIBUTING.md

Tell where to copy the language directories in instructions for testing
